### PR TITLE
First draft at Garnett colors in pasteup.

### PR DESCRIPTION
**Pull request by AWare**
Changes the neutrals and then adds all the new colours.
I think it's worth continuing through all the listed colours and updating them to their garnett values, so this PR is partly to survey and see what people think about this approach and which colours live in pasteup.

### CODE REVIEW

**Comment by SiAdcock** [comment]
Thanks for doing this, @AWare!

I guess we'll need to bump the version in `bower.json`?

I'd love to ask "Should we also update [`guss-colours`](https://github.com/guardian/guss-colours)?" but it's unclear how or whether `guss-colours` are used by `pasteup-palette`.

@sndrs do you have any thoughts or knowledge around this?

**Comment by AWare** [comment]
@SiAdcock guss-colours mostly just links to pasteup-colours here: https://github.com/guardian/guss-colours/blob/master/_colours.config.scss#L4

**Comment by SiAdcock** [comment]
I guess none of these changes (except changes to some of the neutral colours) will be reflected in the [demo](http://guardian.github.io/pasteup-palette/demo/) ([source](https://github.com/guardian/pasteup-palette/blob/master/demo/index.html))

Maybe it would be better to delete old, irrelevant styles and show new ones in the demo? This would require a bit of coordination with someone from design

**Comment by SiAdcock** [comment]
After discussion, let's keep the old pasteup colours intact in the demo and tack the new Garnett colours to the end.

**Comment by AWare** [comment]
Does this represent the full canonical colour set?
https://design.gutools.co.uk/#colour-palette

**Comment by SiAdcock** [comment]
Yeah, that's my understanding. You might want to talk to @blongden73 to confirm

**Comment by AWare** [comment]
This is very old and has been superseded several times.

**Pull request closed without merging**
